#!/usr/bin/env node
/**
 * Compliance gate for the preset library (component-sourcing.md §0.3 step 3).
 *
 * - Validates every `<Name>.meta.json` sidecar has the required provenance
 *   fields (library, source, author, license, attributionRequired, ingest).
 * - Fails when an `attributionRequired: true` component lacks a credit header.
 * - Fails on dep-drift: a component importing a package that isn't declared
 *   in packages/presets/package.json.
 * - Generates NOTICE.md — the aggregate attribution file for everything the
 *   preset library ships.
 *
 * Plain JSON + this check, no schema library. Wired into `npm test` so these
 * are enforced invariants, not conventions.
 */
import { readFileSync, readdirSync, statSync, writeFileSync, existsSync } from 'node:fs'
import { dirname, join, relative } from 'node:path'
import { fileURLToPath } from 'node:url'

const pkgRoot = join(dirname(fileURLToPath(import.meta.url)), '..')
const srcRoot = join(pkgRoot, 'src')

const REQUIRED_FIELDS = ['library', 'source', 'author', 'license', 'attributionRequired', 'ingest']
const INGEST_VALUES = new Set(['registry', 'manual-port', 'rebuilt'])
// Node/runtime modules and the react runtime don't need a dependency entry.
const IMPORT_ALLOW = new Set(['react', 'react-dom'])

const pkg = JSON.parse(readFileSync(join(pkgRoot, 'package.json'), 'utf-8'))
const declaredDeps = new Set([
  ...Object.keys(pkg.dependencies ?? {}),
  ...Object.keys(pkg.devDependencies ?? {}),
  ...Object.keys(pkg.peerDependencies ?? {}),
])

/** Import specifier -> package name ('gsap/ScrollTrigger' -> 'gsap'). */
function packageOf(spec) {
  if (spec.startsWith('.') || spec.startsWith('node:')) return null
  const parts = spec.split('/')
  return spec.startsWith('@') ? parts.slice(0, 2).join('/') : parts[0]
}

function* walk(dir) {
  for (const name of readdirSync(dir)) {
    const p = join(dir, name)
    if (statSync(p).isDirectory()) yield* walk(p)
    else yield p
  }
}

const errors = []
const warnings = []
const credited = [] // { name, file, meta }

const componentFiles = [...walk(srcRoot)].filter((p) => p.endsWith('.tsx') || p.endsWith('.jsx'))
let componentCount = 0
let sidecarless = 0

for (const file of componentFiles) {
  const src = readFileSync(file, 'utf-8')
  const rel = relative(pkgRoot, file)

  // --- dep-drift guard (every component file, sidecar or not) ---
  // Only real import/export statements — JSDoc prose like `from "08"` is not a dep.
  for (const match of src.matchAll(/^(?:import|export)[^\n;]*?\sfrom\s+['"]([^'"]+)['"]/gm)) {
    const dep = packageOf(match[1])
    if (dep && !IMPORT_ALLOW.has(dep) && !declaredDeps.has(dep)) {
      errors.push(`${rel}: imports "${dep}" which is not declared in package.json`)
    }
  }

  // --- per-exported-component sidecar validation ---
  const exports = [...src.matchAll(/export (?:const|function) ([A-Z]\w*)/g)].map((m) => m[1])
  // `export { A, B }` lists (no re-exports from other modules)
  for (const m of src.matchAll(/^export\s*\{([^}]+)\}\s*;?\s*$/gm)) {
    for (const raw of m[1].split(',')) {
      const name = raw.trim().split(/\s+as\s+/).pop()
      if (name && /^[A-Z]\w*$/.test(name) && !exports.includes(name)) exports.push(name)
    }
  }
  for (const name of exports) {
    componentCount++
    const sidecarPath = join(dirname(file), `${name}.meta.json`)
    if (!existsSync(sidecarPath)) {
      sidecarless++
      warnings.push(`${rel}: ${name} has no .meta.json sidecar`)
      continue
    }
    let meta
    try {
      meta = JSON.parse(readFileSync(sidecarPath, 'utf-8'))
    } catch (err) {
      errors.push(`${relative(pkgRoot, sidecarPath)}: invalid JSON (${err.message})`)
      continue
    }
    for (const field of REQUIRED_FIELDS) {
      if (meta[field] === undefined || meta[field] === null || meta[field] === '') {
        errors.push(`${relative(pkgRoot, sidecarPath)}: missing required field "${field}"`)
      }
    }
    if (meta.ingest && !INGEST_VALUES.has(meta.ingest)) {
      errors.push(`${relative(pkgRoot, sidecarPath)}: ingest "${meta.ingest}" is not registry|manual-port|rebuilt`)
    }
    if (meta.attributionRequired === true && !/attribution/i.test(src)) {
      errors.push(`${rel}: ${name} is attributionRequired but the file has no attribution credit header`)
    }
    credited.push({ name, file: rel, meta })
  }
}

// --- NOTICE.md generation ---
const byLibrary = new Map()
for (const c of credited) {
  const key = c.meta.library
  if (!byLibrary.has(key)) byLibrary.set(key, [])
  byLibrary.get(key).push(c)
}
const lines = [
  '# NOTICE',
  '',
  'Third-party and authored components bundled in the Component Style Studio preset',
  'library, with their provenance and licenses. Generated by `npm run build:credits` —',
  'do not edit by hand.',
  '',
]
for (const [library, comps] of [...byLibrary.entries()].sort((a, b) => a[0].localeCompare(b[0]))) {
  const meta = comps[0].meta
  lines.push(`## ${library}`)
  lines.push('')
  lines.push(`- Author: ${meta.author}`)
  lines.push(`- License: ${meta.license}${meta.attributionRequired ? ' — **attribution required**' : ''}`)
  lines.push('')
  lines.push('| Component | File | License | Source |')
  lines.push('|---|---|---|---|')
  for (const c of comps.sort((a, b) => a.name.localeCompare(b.name))) {
    lines.push(`| ${c.name} | \`${c.file}\` | ${c.meta.license} | ${c.meta.source} |`)
  }
  lines.push('')
}
writeFileSync(join(pkgRoot, 'NOTICE.md'), lines.join('\n'))

// --- report ---
console.log(`build:credits — ${componentCount} components, ${credited.length} with sidecars, ${sidecarless} without`)
if (warnings.length > 0 && process.env.CREDITS_VERBOSE) {
  for (const w of warnings) console.warn(`  warn: ${w}`)
}
console.log(`NOTICE.md written (${byLibrary.size} libraries)`)
if (errors.length > 0) {
  for (const e of errors) console.error(`  ERROR: ${e}`)
  console.error(`build:credits FAILED with ${errors.length} error(s)`)
  process.exit(1)
}
